dist: xenial
language: python
python:
  - "3.8"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Envfile via `conda env export | sed -E "s/name: [a-z-]*/name: test-environment/" > tests/environment.yml`
  # TODO: re-enable testing across Python versions using $TRAVIS_PYTHON_VERSION
  - conda env create -f environment.yml && conda activate test-environment
  script:
  - cd tests && mkdir baseline && git clone --depth=1 https://github.com/ResidentMario/geoplot-images.git baseline
  - pytest mixin_tests.py
  - pytest --mpl viz_tests.py
  - pytest --mpl proj_tests.py